### ISSUE TITLE
unable to start exabgpmon

### ISSUE THREAD

**Issue by callumbnz** [thepacketgeek/ExaBGPmon#1]
Love the idea - however when i go to start exabgpmon with the command;

supervisorctl start exabgpmon
exabgpmon: ERROR (no such process)

I suspect it is just missing a conf file for supervisord - are you able to check?

**Comment by thepacketgeek** [comment]
The deployment docs aren't complete and I apologize greatly for that!  I will finish them real quick.  But I think you may just need to do `supervisorctl reread` and `supervisor update` first to read in the exabgpfon process file.

**Comment by callumbnz** [comment]
So - exabgpmon.conf has the config for exabgp to start with the correct config file, etc and it starts fine.

The webapp will not start however, which i assume should have a [program:exabgpmon] section in the supervisor config file somewhere - me being a router monkey and not a code monkey, i'm rapidly running out of talent!

**Comment by thepacketgeek** [comment]
You're exactly right, I lost the exabgpmon process section in the mix and have been running with the debug server locally. 

I also need to add in notes about nginx as a possible front end. If you want to get up and running as that may take a bit of time, go ahead and do this from the exabgpmon folder:
`python manage.py runserver`

You can enable debug, auto-restart, and a port with the following -r[estart] -d[ebug] -p[ort] 8000 keywords:
`python manage.py runserver -rdp 8000`

**Comment by callumbnz** [comment]
Awesome - managed to get it running - love your work :)

Look forward to more updates - if you need any testing - give me a yell.

On Tue, Jul 21, 2015 at 1:45 PM, Mat Wood <notifications@github.com> wrote:

> You're exactly right, I lost the exabgpmon process section in the mix and
> have been running with the debug server locally.
>
> I also need to add in notes about nginx as a possible front end. If you
> want to get up and running as that may take a bit of time, go ahead and do
> this from the exabgpmon folder:
> python manage.py runserver
>
> You can enable debug, auto-restart, and a port with the following
> -r[estart] -d[ebug] -p[ort] 8000 keywords:
> python manage.py runserver -rdp 8000
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thepacketgeek/ExaBGPmon/issues/1#issuecomment-123126635>
> .
>



-- 
Callum Barr
me@callumb.com

**Comment by thepacketgeek** [comment]
Thanks so much! I got a little distracted the last couple weeks but I'll be
diving back in shortly. I need to figure out the testing side of things for
sure.
